In [17]:
import pandas as pd
import numpy as np
import json

## Placeholder Survey Data

In [8]:
df = pd.read_csv('placeholder_data.csv')
df

,id,experience,before,during,after
0,1,0,1,1,3
1,2,0,2,2,2
2,3,1,3,2,1
3,4,1,2,3,1
4,5,2,1,2,1
5,6,3,3,3,2


## Create the data structure `d3.sankey()` expects

In [9]:
experience = ['Never', 'Once/few times before', 'Occasionally', 'Regularly']
before = ['More than typical', 'About typical', 'Less than typical']
during = ['More stressed', 'About the same', 'Less stressed']
after = ['Increased', 'Not much', 'Reduced']

In [15]:
data = []
for e in experience:
    for b in before:
        for d in during:
            for a in after:
                data.append({'experience': e, 'before': b, 'during': d, 'after': a, 'value': 0})
data            

[{'experience': 'Never',
  'before': 'More than typical',
  'during': 'More stressed',
  'after': 'Increased',
  'value': 0},
 {'experience': 'Never',
  'before': 'More than typical',
  'during': 'More stressed',
  'after': 'Not much',
  'value': 0},
 {'experience': 'Never',
  'before': 'More than typical',
  'during': 'More stressed',
  'after': 'Reduced',
  'value': 0},
 {'experience': 'Never',
  'before': 'More than typical',
  'during': 'About the same',
  'after': 'Increased',
  'value': 0},
 {'experience': 'Never',
  'before': 'More than typical',
  'during': 'About the same',
  'after': 'Not much',
  'value': 0},
 {'experience': 'Never',
  'before': 'More than typical',
  'during': 'About the same',
  'after': 'Reduced',
  'value': 0},
 {'experience': 'Never',
  'before': 'More than typical',
  'during': 'Less stressed',
  'after': 'Increased',
  'value': 0},
 {'experience': 'Never',
  'before': 'More than typical',
  'during': 'Less stressed',
  'after': 'Not much',
  'value': 

In [16]:
for row in df.itertuples():
    entry_exp = experience[row.experience]
    entry_before = before[row.before - 1]
    entry_during = during[row.during - 1]
    entry_after = after[row.after - 1]
    
    for entry in data:
        if entry['experience'] == entry_exp and entry['before'] == entry_before and entry['during'] == entry_during and entry['after'] == entry_after:
            entry['value'] += 1
            break
data

[{'experience': 'Never',
  'before': 'More than typical',
  'during': 'More stressed',
  'after': 'Increased',
  'value': 0},
 {'experience': 'Never',
  'before': 'More than typical',
  'during': 'More stressed',
  'after': 'Not much',
  'value': 0},
 {'experience': 'Never',
  'before': 'More than typical',
  'during': 'More stressed',
  'after': 'Reduced',
  'value': 1},
 {'experience': 'Never',
  'before': 'More than typical',
  'during': 'About the same',
  'after': 'Increased',
  'value': 0},
 {'experience': 'Never',
  'before': 'More than typical',
  'during': 'About the same',
  'after': 'Not much',
  'value': 0},
 {'experience': 'Never',
  'before': 'More than typical',
  'during': 'About the same',
  'after': 'Reduced',
  'value': 0},
 {'experience': 'Never',
  'before': 'More than typical',
  'during': 'Less stressed',
  'after': 'Increased',
  'value': 0},
 {'experience': 'Never',
  'before': 'More than typical',
  'during': 'Less stressed',
  'after': 'Not much',
  'value': 

## Placeholder Viewing Angle Data

In [57]:
azimuth_data = np.random.normal(0, 28, 1800)
azimuth_data

array([ 32.39081804,  16.99325891,  14.86937596, ..., -20.98740742,
         7.18730099, -13.26143366])

In [58]:
azimuth_data_binned = np.round(16 * azimuth_data / 360).astype(int)
azimuth_data_binned

array([ 1,  1,  1, ..., -1,  0, -1])

In [59]:
azimuth_data_2d = azimuth_data_binned.reshape(36, 50)
azimuth_data_2d

array([[ 1,  1,  1, ...,  1,  0,  0],
       [ 2,  0,  3, ...,  1, -1,  0],
       [ 1,  2, -2, ...,  0,  1,  0],
       ...,
       [ 0, -1, -1, ...,  0, -1,  0],
       [ 1, -1,  1, ..., -1, -1,  0],
       [ 1, -1, -2, ..., -1,  0, -1]])

In [60]:
heat_input = np.zeros((36, 16)).astype(np.uint8)
for i, row in enumerate(azimuth_data_2d):
    for j in row:
        heat_input[i, j] += 1
heat_input

array([[15, 13,  3,  1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  2,  5, 11],
       [15, 12,  7,  1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  1,  6,  8],
       [15, 14,  6,  1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  6,  8],
       [19,  7,  4,  0,  1,  0,  0,  0,  0,  0,  0,  0,  0,  2,  6, 11],
       [16, 10,  2,  1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  1,  8, 12],
       [18,  7,  6,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  1,  6, 12],
       [19,  9,  6,  1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  1,  4, 10],
       [17, 10,  7,  1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  5, 10],
       [14, 10,  4,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  7, 15],
       [11, 13,  7,  1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  3,  3, 12],
       [17, 13,  4,  1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  1,  4, 10],
       [16,  7,  3,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  1,  3, 20],
       [18, 13,  5,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  3, 11],
       [18, 10,  6,  0,  0,  0,  0,  0,  0,  0,  0,