In [17]:
import pandas as pd
import numpy as np
import json

## Placeholder Survey Data

In [8]:
df = pd.read_csv('placeholder_data.csv')
df

id  experience  before  during  after
0   1           0       1       1      3
1   2           0       2       2      2
2   3           1       3       2      1
3   4           1       2       3      1
4   5           2       1       2      1
5   6           3       3       3      2

## Create the data structure `d3.sankey()` expects

In [9]:
experience = ['Never', 'Once/few times before', 'Occasionally', 'Regularly']
before = ['More than typical', 'About typical', 'Less than typical']
during = ['More stressed', 'About the same', 'Less stressed']
after = ['Increased', 'Not much', 'Reduced']

In [15]:
data = []
for e in experience:
    for b in before:
        for d in during:
            for a in after:
                data.append({'experience': e, 'before': b, 'during': d, 'after': a, 'value': 0})
data            

[{'experience': 'Never',
  'before': 'More than typical',
  'during': 'More stressed',
  'after': 'Increased',
  'value': 0},
 {'experience': 'Never',
  'before': 'More than typical',
  'during': 'More stressed',
  'after': 'Not much',
  'value': 0},
 {'experience': 'Never',
  'before': 'More than typical',
  'during': 'More stressed',
  'after': 'Reduced',
  'value': 0},
 {'experience': 'Never',
  'before': 'More than typical',
  'during': 'About the same',
  'after': 'Increased',
  'value': 0},
 {'experience': 'Never',
  'before': 'More than typical',
  'during': 'About the same',
  'after': 'Not much',
  'value': 0},
 {'experience': 'Never',
  'before': 'More than typical',
  'during': 'About the same',
  'after': 'Reduced',
  'value': 0},
 {'experience': 'Never',
  'before': 'More than typical',
  'during': 'Less stressed',
  'after': 'Increased',
  'value': 0},
 {'experience': 'Never',
  'before': 'More than typical',
  'during': 'Less stressed',
  'after': 'Not much',
  'value': 

In [16]:
for row in df.itertuples():
    entry_exp = experience[row.experience]
    entry_before = before[row.before - 1]
    entry_during = during[row.during - 1]
    entry_after = after[row.after - 1]
    
    for entry in data:
        if entry['experience'] == entry_exp and entry['before'] == entry_before and entry['during'] == entry_during and entry['after'] == entry_after:
            entry['value'] += 1
            break
data

[{'experience': 'Never',
  'before': 'More than typical',
  'during': 'More stressed',
  'after': 'Increased',
  'value': 0},
 {'experience': 'Never',
  'before': 'More than typical',
  'during': 'More stressed',
  'after': 'Not much',
  'value': 0},
 {'experience': 'Never',
  'before': 'More than typical',
  'during': 'More stressed',
  'after': 'Reduced',
  'value': 1},
 {'experience': 'Never',
  'before': 'More than typical',
  'during': 'About the same',
  'after': 'Increased',
  'value': 0},
 {'experience': 'Never',
  'before': 'More than typical',
  'during': 'About the same',
  'after': 'Not much',
  'value': 0},
 {'experience': 'Never',
  'before': 'More than typical',
  'during': 'About the same',
  'after': 'Reduced',
  'value': 0},
 {'experience': 'Never',
  'before': 'More than typical',
  'during': 'Less stressed',
  'after': 'Increased',
  'value': 0},
 {'experience': 'Never',
  'before': 'More than typical',
  'during': 'Less stressed',
  'after': 'Not much',
  'value': 

## Placeholder Viewing Angle Data

In [41]:
azimuth_data = np.random.normal(0, 0.3, 1800) * 180
azimuth_data

array([  55.04181479, -112.19602169,   37.43595198, ..., -105.31364652,
         89.82245797,   33.23489234])

In [48]:
azimuth_data_binned = np.round(16 * azimuth_data / 360).astype(int)
azimuth_data_binned

array([ 2, -5,  2, ..., -5,  4,  1])

In [50]:
azimuth_data_2d = azimuth_data_binned.reshape(36, 50)
azimuth_data_2d

array([[ 2, -5,  2, ...,  0,  0,  0],
       [-2, -2, -1, ...,  1,  2,  0],
       [-1,  2,  0, ...,  0, -5,  0],
       ...,
       [-2,  3, -3, ..., -6, -2,  0],
       [ 0, -5, -1, ...,  4,  1, -5],
       [ 0,  2,  3, ..., -5,  4,  1]])

In [55]:
heat_input = np.zeros((36, 16)).astype(np.uint8)
for i, row in enumerate(azimuth_data_2d):
    for j in row:
        heat_input[i, j] += 1
heat_input

array([[11,  6,  8,  2,  0,  2,  0,  0,  0,  0,  0,  7,  1,  6,  5,  2],
       [ 7,  9, 10,  2,  0,  2,  0,  0,  0,  0,  0,  2,  3,  2,  5,  8],
       [10,  4,  7,  6,  3,  0,  1,  0,  0,  0,  0,  3,  4,  1,  5,  6],
       [ 9,  6,  7,  1,  2,  2,  1,  0,  0,  0,  1,  3,  2,  1,  4, 11],
       [ 5, 12,  4,  1,  2,  2,  1,  1,  0,  0,  0,  0,  1,  8,  5,  8],
       [11, 15,  5,  3,  0,  0,  0,  0,  0,  0,  0,  0,  3,  3,  3,  7],
       [ 7,  2,  5,  5,  0,  1,  1,  0,  1,  0,  0,  2,  4,  6, 11,  5],
       [ 8,  6,  5,  7,  1,  1,  0,  0,  0,  0,  1,  1,  6,  3,  4,  7],
       [10, 11,  4,  5,  3,  0,  0,  0,  0,  0,  1,  2,  1,  1,  8,  4],
       [ 6, 11,  7,  4,  1,  0,  0,  0,  0,  0,  0,  1,  4,  7,  5,  4],
       [ 7, 13,  4,  2,  2,  1,  0,  1,  0,  0,  0,  3,  3,  2,  1, 11],
       [ 4,  8,  9,  2,  3,  0,  0,  1,  0,  0,  1,  0,  0,  4, 12,  6],
       [ 8, 11,  6,  1,  1,  0,  1,  0,  0,  0,  1,  1,  3,  2,  7,  8],
       [ 8,  9,  8,  3,  4,  0,  2,  0,  0,  0,  0,